CREATE TABLE GV_LOG.HL7_MSG
  (
    "ID"        NUMBER(10,0)  NOT NULL PRIMARY KEY,
    "TIMESTAMP" TIMESTAMP (6) NOT NULL,
    "THREAD"    VARCHAR2(50)  NULL,
    "LISTENER"  VARCHAR2(255) NULL,
    "DIRECTION" VARCHAR2(255) NULL,
    "REMOTE_IP" VARCHAR2(16)  NULL,
    "SERVER"    VARCHAR2(255) NULL,
    "MSG"       CLOB NULL
  )