CREATE TABLE "GV_LOG"."HL7_MSG"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE,
    "THREAD"    VARCHAR2(50 BYTE),
    "LISTENER"  VARCHAR2(255 BYTE),
    "DIRECTION" VARCHAR2(255 BYTE),
    "REMOTE_IP" VARCHAR2(16 BYTE),
    "SERVER"    VARCHAR2(255 BYTE),
    "MSG" CLOB,
    CONSTRAINT "HL7_MSG_PK" PRIMARY KEY ("ID") USING INDEX
    TABLESPACE "USERS" ENABLE
  )