CREATE SCHEMA GV_PERS AUTHORIZATION DBA;
CREATE USER "gv_pers" PASSWORD 'gv_pers' ADMIN;
ALTER  USER "gv_pers" SET INITIAL SCHEMA GV_PERS;

CREATE TABLE GV_PERS.GV_RECOVERY_POINT (
    REC_ID          NUMBER(20,0) NOT NULL,
    ID              VARCHAR2(24) NOT NULL,
    SERVER          VARCHAR2(50) NOT NULL,
    SYSTEM          VARCHAR2(255) NOT NULL,
    SERVICE         VARCHAR2(255) NOT NULL,
    OPERATION       VARCHAR2(255) NOT NULL,
    RECOVERY_NODE   VARCHAR2(255) NOT NULL,
    STATE           VARCHAR2(10) NOT NULL,
    CREATION_DATE   TIMESTAMP(6) NOT NULL,
    UPDATE_DATE     TIMESTAMP(6) NOT NULL,
    ENVIRONMENT     BLOB NOT NULL,
    CONSTRAINT GV_PERS.PK_REC_ID PRIMARY KEY(REC_ID),
    CONSTRAINT GV_PERS.UN_REC_POINT UNIQUE (ID, SYSTEM, SERVICE, OPERATION)
);

CREATE TABLE GV_PERS.GV_RECOVERY_PROPERTY (
    REC_ID  NUMBER(20,0) NOT NULL,
    NAME    VARCHAR2(255) NOT NULL,
    VALUE   CLOB NULL,
    CONSTRAINT GV_PERS.PK_REC_PAR PRIMARY KEY(REC_ID,NAME),
    CONSTRAINT GV_PERS.FK_REC FOREIGN KEY(REC_ID) REFERENCES GV_PERS.GV_RECOVERY_POINT(REC_ID)
);

CREATE SEQUENCE GV_PERS.RECOVERY_SEQ
    INCREMENT BY 1
    START WITH 1;
