CREATE SCHEMA GV_STATS AUTHORIZATION DBA;
CREATE USER "gv_stats" PASSWORD 'gv_stats' ADMIN;
ALTER USER "gv_stats" SET INITIAL SCHEMA GV_STATS;

CREATE TABLE GV_STATS.SERVICE_INFORMATIONS (
    SYSTEM          VARCHAR2(100) NOT NULL,
    SERVICE         VARCHAR2(100) NOT NULL,
    ID              VARCHAR2(24) NOT NULL,
    START_TIME      NUMBER(20,0) NOT NULL,
    STOP_TIME       NUMBER(20,0) NOT NULL,
    START_DATE      TIMESTAMP(6) NOT NULL,
    STOP_DATE       TIMESTAMP(6) NOT NULL,
    STATE           NUMBER(10,0) NULL,
    ERROR_CODE      NUMBER(10,0) NULL,
    PACKAGE_NAME    VARCHAR2(250) NOT NULL,
    PROCESS_NAME    VARCHAR2(250) NOT NULL,
    PROCESS_TIME    NUMBER(20,0) NOT NULL
);
