#created on: 10-feb-2012
package tests.unit.gvrules.bean.license

#list any import classes here.
import tests.unit.gvrules.bean.license.Applicant;
import tests.unit.gvrules.bean.license.Application;


#declare any global variables here


rule "Is of valid age"
when
    Applicant( age < 18 )
    $a : Application()     
then
    $a.setValid( false );
end

rule "Application was made this year"
when
    $a : Application( dateApplied > "01-jan-2014" )
then
    $a.setValid( false );
end