// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package it.greenvulcano.gvesb.rsh.server.rmi;

public final class RSHServiceImpl_Stub extends java.rmi.server.RemoteStub implements
        it.greenvulcano.gvesb.rsh.server.rmi.RSHService, java.rmi.Remote
{
    private static final long               serialVersionUID = 2;

    private static java.lang.reflect.Method $method_getFile_0;
    private static java.lang.reflect.Method $method_sendFile_1;
    private static java.lang.reflect.Method $method_shellExec_2;

    static {
        try {
            $method_getFile_0 = it.greenvulcano.gvesb.rsh.server.rmi.RSHService.class.getMethod("getFile",
                    new java.lang.Class[]{java.lang.String.class});
            $method_sendFile_1 = it.greenvulcano.gvesb.rsh.server.rmi.RSHService.class.getMethod(
                    "sendFile",
                    new java.lang.Class[]{java.lang.String.class, com.healthmarketscience.rmiio.RemoteInputStream.class});
            $method_shellExec_2 = it.greenvulcano.gvesb.rsh.server.rmi.RSHService.class.getMethod("shellExec",
                    new java.lang.Class[]{it.greenvulcano.gvesb.rsh.server.cmd.helper.ShellCommandDef.class});
        }
        catch (java.lang.NoSuchMethodException e) {
            throw new java.lang.NoSuchMethodError("stub class initialization failed");
        }
    }

    // constructors
    public RSHServiceImpl_Stub(java.rmi.server.RemoteRef ref)
    {
        super(ref);
    }

    // methods from remote interfaces

    // implementation of getFile(String)
    @Override
    public com.healthmarketscience.rmiio.RemoteInputStream getFile(java.lang.String $param_String_1)
            throws it.greenvulcano.gvesb.rsh.RSHException, java.rmi.RemoteException
    {
        try {
            Object $result = ref.invoke(this, $method_getFile_0, new java.lang.Object[]{$param_String_1},
                    -3494612659481588766L);
            return ((com.healthmarketscience.rmiio.RemoteInputStream) $result);
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.rmi.RemoteException e) {
            throw e;
        }
        catch (it.greenvulcano.gvesb.rsh.RSHException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of sendFile(String, RemoteInputStream)
    @Override
    public void sendFile(java.lang.String $param_String_1,
            com.healthmarketscience.rmiio.RemoteInputStream $param_RemoteInputStream_2)
            throws it.greenvulcano.gvesb.rsh.RSHException, java.rmi.RemoteException
    {
        try {
            ref.invoke(this, $method_sendFile_1, new java.lang.Object[]{$param_String_1, $param_RemoteInputStream_2},
                    -9108544457034698505L);
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.rmi.RemoteException e) {
            throw e;
        }
        catch (it.greenvulcano.gvesb.rsh.RSHException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }

    // implementation of shellExec(ShellCommandDef)
    @Override
    public it.greenvulcano.gvesb.rsh.server.cmd.helper.ShellCommandResult shellExec(
            it.greenvulcano.gvesb.rsh.server.cmd.helper.ShellCommandDef $param_ShellCommandDef_1)
            throws it.greenvulcano.gvesb.rsh.RSHException, java.rmi.RemoteException
    {
        try {
            Object $result = ref.invoke(this, $method_shellExec_2, new java.lang.Object[]{$param_ShellCommandDef_1},
                    8771592846415270156L);
            return ((it.greenvulcano.gvesb.rsh.server.cmd.helper.ShellCommandResult) $result);
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.rmi.RemoteException e) {
            throw e;
        }
        catch (it.greenvulcano.gvesb.rsh.RSHException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new java.rmi.UnexpectedException("undeclared checked exception", e);
        }
    }
}
