
DROP TABLE GV_RECOVERY_PROPERTY
/

DROP TABLE GV_RECOVERY_POINT
/

CREATE TABLE GV_RECOVERY_POINT (
    REC_ID          NUMBER NOT NULL,
    ID              VARCHAR2(24) NOT NULL,
    SERVER          VARCHAR2(50) NOT NULL,
    SYSTEM          VARCHAR2(255) NOT NULL,
    SERVICE         VARCHAR2(255) NOT NULL,
    OPERATION       VARCHAR2(255) NOT NULL,
    RECOVERY_NODE   VARCHAR2(255) NOT NULL,
    STATE           VARCHAR2(10) NOT NULL,
    CREATION_DATE   DATE NOT NULL,
    UPDATE_DATE     DATE NOT NULL,
    ENVIRONMENT     BLOB NOT NULL,
    CONSTRAINT PK_REC_ID PRIMARY KEY(REC_ID)
    NOT DEFERRABLE
     VALIDATE
)
/

ALTER TABLE GV_RECOVERY_POINT
    ADD ( CONSTRAINT UN_REC_POINT
    UNIQUE (ID, SYSTEM, SERVICE, OPERATION)
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/

/

CREATE TABLE GV_RECOVERY_PROPERTY (
    REC_ID  NUMBER NOT NULL,
    NAME    VARCHAR2(255) NOT NULL,
    VALUE   CLOB NULL,
    CONSTRAINT PK_REC_PAR PRIMARY KEY(REC_ID,NAME)
    NOT DEFERRABLE
     VALIDATE
)
/

ALTER TABLE GV_RECOVERY_PROPERTY
    ADD ( CONSTRAINT FK_REC
    FOREIGN KEY(REC_ID)
    REFERENCES GV_RECOVERY_POINT(REC_ID)
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE )
/


DROP SEQUENCE RECOVERY_SEQ
/

CREATE SEQUENCE RECOVERY_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    CACHE 20
    ORDER
/